<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Enter' => 'Invio',
    'Error while saving record!' => 'Errore durante il salvataggio dei dati!',
    'Model {class} not found by primary key "{pk}"' => 'Regole base {class} non trovate attraverso la primary key "{pk}"',
    'Model {class} rules do not allow to update attribute "{attr}"' => 'Le regole base {class} non permettono di aggiornare la caratteristica "{attr}"',
    'Property "attribute" should be defined.' => 'Definire la proprietà "attribute"',
    'Property "primaryKey" should be defined.' => 'Definire la proprietà "primaryKey"',
    'You should provide modelClass in constructor of EditableSaver.' => 'Fornisci la caratteristica del modello nella construzione del form',
    'x clear' => 'x cancella',
);
